---
- hosts: all
  become: yes
  tasks:
    - name: Enable root login in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^\s*#?\s*PermitRootLogin\s+.*'
        line: 'PermitRootLogin yes'
        state: present
        backup: yes
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted