- name: Get AWS EC2 Instances with vaulted credentials
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: ec2_instance_name
      prompt: "Enter ec2 instance name"
      private: false   # Set to true for hidden input (like a password)

  vars:
    instance_id: "{{ ec2_instance_name }}"
    ami_name: my-ami-20240720
    region: ap-southeast-2

  tasks:
    - name: Create AMI from the specified EC2 instance
      amazon.aws.ec2_ami:
        instance_id: "{{ ec2_instance_name }}"
        name: "{{ ami_name }}"
        region: "{{ region }}"
        wait: true
        tags:
          CreatedBy: Ansible
          SourceInstance: "{{ instance_id }}"
      register: ami_result

    - name: Display AMI information
      debug:
        var: ami_result
